name: Think of IT Digital Marketing
favicon: null
layout_spectrum: 0.29620388126932085
typography_spectrum: 0.963799468241632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.777445308631286
  lightness: 0.7575433023739606
  saturation: 0.6072563047055155
  rhythmicContrast: 0.08822953584603965
purpose: []
