name: Think of IT Digital Marketing
favicon: null
layout_spectrum: 0.29620388126932085
typography_spectrum: 0.963799468241632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffde00'
    - '#ffffff'
    - '#bbbcbe'
    - '#938a59'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
